In [2]:
import numpy as np

a=np.array([1,2,3])
print('1D array:')
print(a)
print()
b=np.array([(1,2,3),(4,5,6)])
print('2D array:')
print(b)

1D array:
[1 2 3]

2D array:
[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
import sys

S = range(1000)
print('Resultado liste de Python')
print(sys.getsizeof(5)*len(S))
print()
D = np.arange(1000)
print('Resultado NumPy array:')
print(D.size*D.itemsize)

Resultado liste de Python
28000

Resultado NumPy array:
8000


In [7]:
import numpy as np
import time

SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print('Resultado lista de Python')
print((time.time()-start)*1000)
print()
start = time.time()
result = A1 + A2
print('Resultado NumPy array:')
print((time.time()-start)*1000)

Resultado lista de Python
159.8834991455078

Resultado NumPy array:
34.365177154541016
