In [2]:
import numpy as np

a=np.array([1,2,3])
print('1D array:')
print(a)
print()
b=np.array([(1,2,3),(4,5,6)])
print('2D array:')
print(b)

1D array:
[1 2 3]

2D array:
[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
import sys

S = range(1000)
print('Resultado liste de Python')
print(sys.getsizeof(5)*len(S))
print()
D = np.arange(1000)
print('Resultado NumPy array:')
print(D.size*D.itemsize)

Resultado liste de Python
28000

Resultado NumPy array:
8000


In [7]:
import numpy as np
import time

SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print('Resultado lista de Python')
print((time.time()-start)*1000)
print()
start = time.time()
result = A1 + A2
print('Resultado NumPy array:')
print((time.time()-start)*1000)

Resultado lista de Python
159.8834991455078

Resultado NumPy array:
34.365177154541016


In [2]:
import numpy as np
import pandas as pd

data = np.array([['','Col1', 'Col2'], ['Fila1', 11, 22], ['Fila2', 33, 44]])
print(pd.DataFrame(data=data[1:,1:], index=data[1:,0], columns = data[0,1:]))

      Col1 Col2
Fila1   11   22
Fila2   33   44


In [3]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print('DataFrame:')
print(df)

DataFrame:
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [5]:
series = pd.Series({"Argentina":"Buenos Aires",
                   "Chile":"Santiago de Chile",
                   "Colombia":"Bogotá",
                   "Perú":"Lima"})
print('Series:')
print(series)

Series:
Argentina         Buenos Aires
Chile        Santiago de Chile
Colombia                Bogotá
Perú                      Lima
dtype: object
